### ISSUE TITLE
Some General Docs Tasks

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/node#109]
Some initial ideas

* [x] `rapids-js` -> `node-rapids` throughout (#113)
* [x] audit what is/is not included in ref guide
* [ ] images/vids in the demo READMEs
* [ ] link to demos from the docs
* [ ] copy/paste-able code snippets, examples, etc.
* [ ] expanded narrative docs, e.g [explain groupby in general](https://github.com/rapidsai/node-rapids/pull/108/files#r592823402)

cc @trxcllnt @AjayThorve

**Comment by trxcllnt** [comment]
also we should find-replace `/s/rapids-js/node-rapids` in any docstrings/markdown files.

**Comment by exactlyallan** [comment]
@AjayThorve yeah readme is already out of date! ;)

**Comment by AjayThorve** [comment]
> @AjayThorve yeah readme is already out of date! ;)

fix applied in #113, thanks to @ajschmidt8

**Comment by AjayThorve** [comment]
@bryevdv for the example snippets, how does [this](https://rapidsai.github.io/node-rapids/classes/cudf_src.dataframe.html#nanstonulls) look?

**Comment by bryevdv** [comment]
@AjayThorve I think that looks fantastic and that snippets like that will be super helpful for users. Ideally, eventually we find some way to put examples under test so that that can't go stale. I am not sure what would be involved with that here. (Only comment: FWIW I find col names like "a" and "b" easier to read than "ser_0" and "ser_1" but either way is good!)

**Comment by AjayThorve** [comment]
> [1] In both Azure for Python and Bokeh examples were in their own scripts that were run to check for errors on CI, and then the Sphinx could inject the script into the docs source code on docs build. But I am not sure what typedoc can do if anything in this vein.

Interesting!! As of now typedoc is picking the example straight from the docstring, I'll check if there are ways to inject examples from scripts

**Comment by exactlyallan** [comment]
Fixed with #383
