### ISSUE TITLE
Broken Demos

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/node#125]
In my recent exploration of all the `node-rapids` demos, I found some that aren't working for me. I've looked at the source code of a few briefly with Paul, but we weren't able to quickly find a resolution, so I wanted to document them here.

They can be categorized as follows (ticked boxes mean they've been fixed):

**No errors in terminal, blank window appears**:

- [ ] 3 (`modules/demo/graph`) - window opens with text stats, but no graphics are shown
- [ ] 28 (`modules/demo/deck/data-filter`)
- [x] 29 (`modules/demo/deck/brushing`) - (works now, but missing background map. potentially due to Mapbox changes)
- [x] 31 (`modules/demo/deck/arc`) - (works now, but missing background map. potentially due to Mapbox changes)
- [x] 24 (`modules/demo/deck/heatmap`) 
- [x] 34 (`modules/demo/deck/3d-heatmap`)

**Stacktraces are displayed in terminal**:

- [ ] 9 (`modules/demo/deck/trips`)
- [ ] 14 (`modules/demo/deck/point-cloud`)
- [ ] 16 (`modules/demo/deck/playground`)
- [ ] 18 (`modules/demo/deck/map-tile`) - Unhandled promise exception (possibly due to 404 from [this link](https://github.com/rapidsai/node-rapids/blob/main/modules/demo/deck/map-tile/app.js#L47))
- [ ] 21 (`modules/demo/deck/image-tile`) - Unhandled promise exception (possibly due to 404 from [this link](https://github.com/rapidsai/node-rapids/blob/main/modules/demo/deck/image-tile/app.js#L15))
- [ ] 22 (`modules/demo/deck/icon`)
- [ ] 25 (`modules/demo/deck/h3-grid`)
- [ ] 32 (`modules/demo/deck/ShanghaiData`) - [basemap.geojson URL](https://github.com/rapidsai/node-rapids/blob/main/modules/demo/deck/ShanghaiData/app.js#L17) 404s
- [ ] 33 (`modules/demo/deck/3d-tiles`)

**Miscellaneous**:

- [ ] 6 (`modules/demo/tfjs/webgl-tests`) - alternates between 1 & 3 test failures each time I run it

**Comment by trxcllnt** [comment]
> 6 (modules/demo/tfjs/webgl-tests) - alternates between 1 & 3 test failures each time I run it

This is expected at the moment. Need to nail down why some of the tfjs tests non-deterministically fail.

**Comment by trxcllnt** [comment]
The blank windows seem to be caused by switching the `openGLProfile` for GLFW from `GLFWOpenGLProfile.ANY` to `GLFWOpenGLProfile.COMPAT`. I did this to fix the TensorFlow.js tests assuming it'd work for everything, but apparently not. We can make the demos using TensorFlow.js pass `GLFWOpenGLProfile.COMPAT` explicitly.

**Comment by trxcllnt** [comment]
@ajschmidt8 I found out why some of the demos aren't working. I think we had a different way of launching them last summer, but forgot to update the demos for the new API. Fixed a few of them here: https://github.com/rapidsai/node-rapids/pull/127/commits/1c0e293c4aa44a8697e824c6beb688acc12d759b

**Comment by ajschmidt8** [comment]
awesome! I'll go back through these on Monday to re-check them. I updated my original comment above to include some check boxes that I'll tick off for the ones that are fixed.

**Comment by trxcllnt** [comment]
I believe we've fixed or removed any broken demos.
